-- ==============================================================================
-- Cocoon Studio Supabase Schema (100% Idempotent - Safe to Run Multiple Times)
-- Copy and paste this directly into Supabase SQL Editor and click "Run"
-- ==============================================================================

-- 1. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_email TEXT,
    address TEXT NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    total_amount NUMERIC NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'Processing',
    payment_method TEXT DEFAULT 'UPI',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create Customizations Inquiries Table
CREATE TABLE IF NOT EXISTS public.customizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id TEXT NOT NULL UNIQUE,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_email TEXT,
    product_name TEXT,
    category TEXT,
    colorway TEXT,
    idea TEXT,
    needed_by TEXT,
    budget TEXT,
    social_link TEXT,
    media_name TEXT,
    media_url TEXT,
    status TEXT NOT NULL DEFAULT 'New',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Create Customer Reviews Table
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id TEXT NOT NULL UNIQUE,
    product_id BIGINT NOT NULL,
    product_name TEXT NOT NULL,
    customer_name TEXT NOT NULL,
    customer_phone TEXT,
    rating INTEGER NOT NULL DEFAULT 5,
    title TEXT,
    comment TEXT NOT NULL,
    media_url TEXT,
    order_id TEXT,
    status TEXT NOT NULL DEFAULT 'Approved',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Create 1-Time Unique Review Coupons Table (Prevents Reuse Loophole)
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_code TEXT NOT NULL UNIQUE,
    discount_percent INTEGER NOT NULL DEFAULT 15,
    is_used BOOLEAN NOT NULL DEFAULT false,
    order_id TEXT,
    review_id TEXT,
    customer_name TEXT,
    customer_phone TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    used_order_id TEXT,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

-- 6. Policies for Orders (Drop if exists first to avoid 42710 error)
DROP POLICY IF EXISTS "Allow public insert for orders" ON public.orders;
DROP POLICY IF EXISTS "Allow public select for orders" ON public.orders;
DROP POLICY IF EXISTS "Allow public update for orders" ON public.orders;

CREATE POLICY "Allow public insert for orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select for orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow public update for orders" ON public.orders FOR UPDATE USING (true);

-- 7. Policies for Customizations (Drop if exists first)
DROP POLICY IF EXISTS "Allow public insert for customizations" ON public.customizations;
DROP POLICY IF EXISTS "Allow public select for customizations" ON public.customizations;
DROP POLICY IF EXISTS "Allow public update for customizations" ON public.customizations;

CREATE POLICY "Allow public insert for customizations" ON public.customizations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select for customizations" ON public.customizations FOR SELECT USING (true);
CREATE POLICY "Allow public update for customizations" ON public.customizations FOR UPDATE USING (true);

-- 8. Policies for Reviews (Drop if exists first)
DROP POLICY IF EXISTS "Allow public insert for reviews" ON public.reviews;
DROP POLICY IF EXISTS "Allow public select for reviews" ON public.reviews;
DROP POLICY IF EXISTS "Allow public update for reviews" ON public.reviews;

CREATE POLICY "Allow public insert for reviews" ON public.reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select for reviews" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Allow public update for reviews" ON public.reviews FOR UPDATE USING (true);

-- 9. Policies for Coupons (Drop if exists first)
DROP POLICY IF EXISTS "Allow public insert for coupons" ON public.coupons;
DROP POLICY IF EXISTS "Allow public select for coupons" ON public.coupons;
DROP POLICY IF EXISTS "Allow public update for coupons" ON public.coupons;

CREATE POLICY "Allow public insert for coupons" ON public.coupons FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select for coupons" ON public.coupons FOR SELECT USING (true);
CREATE POLICY "Allow public update for coupons" ON public.coupons FOR UPDATE USING (true);

-- 10. Storage Bucket Setup ('cocoon-media')
INSERT INTO storage.buckets (id, name, public) 
VALUES ('cocoon-media', 'cocoon-media', true)
ON CONFLICT (id) DO NOTHING;

-- 11. Storage Policies for Public Upload & Read (Drop if exists first)
DROP POLICY IF EXISTS "Public Read Access" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert Access" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Access" ON storage.objects;

CREATE POLICY "Public Read Access" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'cocoon-media');

CREATE POLICY "Public Insert Access" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'cocoon-media');
